"""Add invoice_date to DeliveryOrder model

Revision ID: af7beeffc35e
Revises: 
Create Date: 2025-05-17 08:48:17.729907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7beeffc35e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_sequences')
    op.add_column('delivery_orders', sa.Column('invoice_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_orders', 'invoice_date')
    op.create_table('daily_sequences',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('last_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('date', name='daily_sequences_pkey')
    )
    # ### end Alembic commands ###
